### ISSUE TITLE
可以上传到anki addon吗

### ISSUE THREAD

**Issue by SOREMUZ** [sirius-fan/FastWordQuery#1]
大大可否把fork的内容上传到这里 https://ankiweb.net/shared/addons/2.1
这样以后有更新的话就能直接在anki的app里更新了

**Comment by Mickychen00** [comment]
+10086

**Comment by sirius-fan** [comment]
下个月我再改改再传上去，毕业季事情稍多

**Comment by sirius-fan** [comment]
103636257

**Comment by sirius-fan** [comment]
https://ankiweb.net/shared/info/103636257
