### ISSUE TITLE
插件更新后anki工具栏中出现两个fastWQ

### ISSUE THREAD

**Issue by person2217** [sirius-fan/FastWordQuery#11]
如标题所示，问题出现于8月19日的更新。
附截图：
![Snipaste_2023-08-20_19-21-49](https://github.com/sirius-fan/FastWordQuery/assets/106829332/dbfac86d-8be5-4ae5-95a7-7c2cc9af5515)

**Comment by sirius-fan** [comment]
我这没有出现。
点击一下插件，看一下有几个FastWordQuery-Qt6，如果有两个，再分别选中，点右下角插件文件看所在文件夹是不是103636257，

**Comment by person2217** [comment]
![image](https://github.com/sirius-fan/FastWordQuery/assets/106829332/ef3c2b39-28a2-4830-b479-dc8257a72f51)

![image](https://github.com/sirius-fan/FastWordQuery/assets/106829332/b8d453e9-525b-4942-af24-49cad4c1a2b4)
确认了一下，都没问题.
我的anki版本是 
版本 ⁨2.1.64 (581f82c5)⁩
Python 3.9.15 Qt 6.4.3 PyQt 6.4.0

**Comment by sirius-fan** [comment]
![image](https://github.com/sirius-fan/FastWordQuery/assets/25720015/f2d5b80e-f995-496b-b551-daa83615c9a7)
你这显然有两个

**Comment by person2217** [comment]
那我理解安装方法错了。
![image](https://github.com/sirius-fan/FastWordQuery/assets/106829332/44cadc4b-31f3-4efa-92ed-d705d0fd0085)
github上的 src是放在本插件文件夹103636257里面吗？

**Comment by sirius-fan** [comment]
我应该说或者的😂，二选一即可

**Comment by person2217** [comment]
我两个都做了，以为是分步骤。现在没问题了
