### ISSUE TITLE
部分单词含义未能正确导入（俄语）

### ISSUE THREAD

**Issue by person2217** [sirius-fan/FastWordQuery#15]
俄语词汇中有й这个字母时，fastwq不能正确导入内容。
该词典在goldendict中能看到内容及示意。但部分词汇在fastwq中未能导入。
希望能进行bug修补。
![image](https://github.com/sirius-fan/FastWordQuery/assets/106829332/b706968f-61e0-472c-af57-4dd9f4eea18d)
![image](https://github.com/sirius-fan/FastWordQuery/assets/106829332/0611517d-0c3a-4d3a-b4e0-e3002a04879a)
词典：
链接：https://pan.baidu.com/s/1nQ_QGQc5DVM_hIZWk2ZuHQ?pwd=y7fi 
提取码：y7fi
anki测试卡片：
链接：https://pan.baidu.com/s/1Vnk4vfX4ppHa1YhErBTmZg?pwd=dbmo 
提取码：dbmo

**Comment by person2217** [comment]
具体故障表现为：anki测试卡片中back字段中空白的词汇

**Comment by sirius-fan** [comment]
我用这个词查到了结果 йог
![image](https://github.com/sirius-fan/FastWordQuery/assets/25720015/5a55b792-105f-4424-a769-347c79463cbc)

你能发一下你查不到的词吗，我这里打不出来俄语，我翻了半天词典才找到 йог

**Comment by person2217** [comment]
我上传的anki测试卡片（百度网盘）
![截图_20230909121931](https://github.com/sirius-fan/FastWordQuery/assets/106829332/342a0efb-ece4-4a58-a19f-457684e6abaa)
里面back是空白的就是（大概600+个单词）

**Comment by person2217** [comment]
我重新导出了问题词汇（链接中都是）
链接：https://pan.baidu.com/s/1z-7GtnQTbP3MpMeWSDxLAQ?pwd=zzre 
提取码：zzre

**Comment by person2217** [comment]
我复制下来几个：（有重音ё也无效）
ребёночек
изумлённо
несерьёзный
кадровый

**Comment by sirius-fan** [comment]
我真能查到😂
第一个
![image](https://github.com/sirius-fan/FastWordQuery/assets/25720015/86297b87-4259-479d-87a1-3755659ecb2c)
![image](https://github.com/sirius-fan/FastWordQuery/assets/25720015/c9540485-3033-4608-9763-20402a64cefc)

---
第二个 goldendict 里面查不到
![image](https://github.com/sirius-fan/FastWordQuery/assets/25720015/d3a432bc-c33d-482a-bdcd-b6eefc0bbbdd)


---
第三个
несерьёзный
![image](https://github.com/sirius-fan/FastWordQuery/assets/25720015/c96adcc1-a41b-49d7-8503-8218e3e12d8d)

![image](https://github.com/sirius-fan/FastWordQuery/assets/25720015/5da1a4ad-3722-43d7-babc-45d2629eae0c)
---
第四个
![image](https://github.com/sirius-fan/FastWordQuery/assets/25720015/c6d884ca-4b70-4d1f-9eb1-b2fb29a0331d)

**Comment by sirius-fan** [comment]
你查下试试，
如果还不行，你试试，取消勾选跳过有值项

**Comment by sirius-fan** [comment]
[ru15k.zip](https://github.com/sirius-fan/FastWordQuery/files/12564610/ru15k.zip)

这个是我查完的，你开个测试账户试试，别在你用的账户试。

**Comment by person2217** [comment]
![Uploading 截图_20230909130122.gif…]()

**Comment by person2217** [comment]
我试试

**Comment by person2217** [comment]
![截图_20230909130122](https://github.com/sirius-fan/FastWordQuery/assets/106829332/f016e271-1805-478d-86f2-9dc30d81f37a)

**Comment by person2217** [comment]
我重装了一下插件，现在正常了。可能上次我装了两次FastWordQuery文件bug了。
非常感谢，你的帮助
