### ISSUE TITLE
 24.04版本anki中报错了（已解决）/Error in the 24.04 version of Anki (fixed)

### ISSUE THREAD

**Issue by aiaiads** [sirius-fan/FastWordQuery#27]
原因可能是anki更新日志中的Adjust HTML editor / add-on config editor font (https://github.com/ankitects/anki/pull/3054)
[editaddon.py](https://github.com/ankitects/anki/commit/3d184073d7ac11128e34cd21e823bcdcbdeb0251#diff-7874cece466645598d217e371561155a613d2e2ea7101c728b9251c6f639fad0)，[editaddon.ui](https://github.com/ankitects/anki/commit/3d184073d7ac11128e34cd21e823bcdcbdeb0251#diff-6b4fd38f07623cdc43c349b67f7bdd449a889328c33494806b7053479bd49567)文件被删除

报错如下：Anki 24.04 (b84fce48)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22621

Traceback (most recent call last):
  File "aqt.progress", line 119, in handler
  File "aqt.main", line 218, in on_window_init
  File "aqt.main", line 265, in setupProfileAfterWebviewsLoaded
  File "aqt.main", line 317, in setupProfile
  File "aqt.main", line 496, in loadProfile
  File "_aqt.hooks", line 4107, in __call__
  File "anki.hooks", line 34, in runHook
  File "C:\Users\a2358\AppData\Roaming\Anki2\addons21\103636257\__init__.py", line 37, in start_here
    from . import common as fastwq
  File "C:\Users\a2358\AppData\Roaming\Anki2\addons21\103636257\common.py", line 29, in <module>
    from .gui import show_about_dialog, show_options  # , check_updates
  File "C:\Users\a2358\AppData\Roaming\Anki2\addons21\103636257\gui\__init__.py", line 3, in <module>
    from .common import *
  File "C:\Users\a2358\AppData\Roaming\Anki2\addons21\103636257\gui\common.py", line 29, in <module>
    from .dictmanager import DictManageDialog
  File "C:\Users\a2358\AppData\Roaming\Anki2\addons21\103636257\gui\dictmanager.py", line 23, in <module>
    from aqt.forms.editaddon import Ui_Dialog
ModuleNotFoundError: No module named 'aqt.forms.editaddon'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AJT Merge Notes ['1425504015', 2023-10-25T03:54, 'None', '']
Advanced Copy Fields ['1898445115', 2024-01-09T01:01, 'v0.4.01', '']
Anki Simulator ['817108664', 2023-11-07T01:26, 'None', '']
AnkiConnect ['2055492159', 2023-10-30T01:44, 'None', '']
Audio Playback Controls ['312734862', 2023-04-23T07:25, 'None', mod]
AwesomeTTS - Add speech to your flashcards ['1436550454', 2023-07-25T07:48, 'None', '']
Batch Editing ['291119185', 2023-10-26T08:38, 'None', '']
FSRS4Anki Helper ['759844606', 2023-11-23T12:25, 'None', mod]
FastWordQuery-Qt6 ['103636257', 2023-11-18T01:38, 'None', '']
Remove Cloze Button and Hotkey ['1966460736', 2022-05-21T18:29, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T09:43, 'None', '']

===IDs of active AnkiWeb add-ons===
103636257 1425504015 1436550454 1771074083 1898445115 1966460736 2055492159 291119185 312734862 759844606 817108664

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Additional Card Fields Fork for 21 ['744725736', 2022-10-23T18:10, 'None', '']
Advanced Browser ['874215009', 2023-07-02T03:55, 'None', '']
Control Audio Playback Pause Skip backwardsforwards Stop Audio ['control_audio-master', 2020-02-04T07:32, 'None', '']
Customize Keyboard Shortcuts ['24411424', 2023-11-01T17:17, 'None', '']
Edit Field During Review ['1020366288', 2022-08-30T03:38, 'None', '']
Enhance main window ['877182321', 2023-10-23T04:28, 'None', mod]
Enhanced Cloze for Anki 21 ['1990296174', 2023-09-11T02:48, 'None', '']
Fast Word Query Multi-threaded queries for words from local or web dictionaries ['1807206748', 2019-06-23T11:10, 'None', '']
Highlight Code ['112228974', 2023-10-15T00:46, 'None', '']
HyperTTS - Add speech to your flashcards ['111623432', 2023-11-20T22:32, 'None', mod]
Leaderboard ['41708974', 2023-01-15T18:53, 'None', mod]
Life Drain ['715575551', 2023-11-07T20:24, 'None', mod]
Minimize to tray ['85158043', 2022-05-01T01:57, 'None', '']
No Distractions Full Screen ['5049862214', 0, 'v4.1.8', mod]
Remaining time for Anki 21 ['1508357010', 2020-12-13T22:14, '20.12.13i151', '']
Syntax Highlighting for Code ['1463041493', 2018-10-07T09:31, 'None', '']
Word Query ['775418273', 2018-01-01T01:07, 'None', '']
extended editor for field for tables searchreplace ['805891399', 2023-07-31T22:12, 'None', '']
syntax highlighting FORK css only night-mode ['1100811177', 2023-03-20T02:08, 'None', mod]

**Comment by SOREMUZ** [comment]
我也是这个报错

**Comment by aiaiads** [comment]
> 我也是这个报错

修改fwq插件文件夹里的dictmanager.py里的内容。

**Comment by aiaiads** [comment]
[新建 文本文档.txt](https://github.com/sirius-fan/FastWordQuery/files/14734750/default.txt)
就是这个文件里的内容，全部复制进去就行

**Comment by SOREMUZ** [comment]
> [新建 文本文档.txt](https://github.com/sirius-fan/FastWordQuery/files/14734750/default.txt) 就是这个文件里的内容，全部复制进去就行

谢谢您，成功了，我把sys.path.append('C:/Users/a2358/AppData/Roaming/Anki/addons21/103636257/gui/my_editaddon')这一行删了也可以用，不知道为什么

**Comment by aiaiads** [comment]
> > [新建 文本文档.txt](https://github.com/sirius-fan/FastWordQuery/files/14734750/default.txt) 就是这个文件里的内容，全部复制进去就行
> 
> 谢谢您，成功了，我把sys.path.append('C:/Users/a2358/AppData/Roaming/Anki/addons21/103636257/gui/my_editaddon')这一行删了也可以用，不知道为什么

不客气，删了也没事，那是我照着gpt4说的用的另一种解决方案，没成功，也没删。

**Comment by Zarves76** [comment]
> [新建 文本文档.txt](https://github.com/sirius-fan/FastWordQuery/files/14734750/default.txt) 就是这个文件里的内容，全部复制进去就行

非常感谢

**Comment by sirius-fan** [comment]
已修复

**Comment by aiaiads** [comment]
> 已修复

是不是还修复了添加卡片的时候选中卡顿的问题，刚跟新了一下流畅多了
