### ISSUE TITLE
字典有不同解释时fwq无法查询出内容

### ISSUE THREAD

**Issue by SOREMUZ** [sirius-fan/FastWordQuery#7]
比如我搜尼寺，欧路词典会如下图所示出现两个意思，但是fwq无法查询直接显示空白，这种情况多存在于日语词典里，特别是一个单词有多个读音的情况，大佬闲下来可以修复下吗

<img width="651" alt="image" src="https://github.com/sirius-fan/FastWordQuery/assets/64671591/0377cc2e-b5fa-4d30-bf3a-a3a7e94c19ad">

测试的词典是这个：链接: https://pan.baidu.com/s/16dBV2iU25Y-P_8CE3Ixj_g?pwd=7c1e 提取码: 7c1e

**Comment by xavier-007** [comment]
我大概能猜到问题，待我测一下

**Comment by xavier-007** [comment]
上错号了。。

**Comment by SOREMUZ** [comment]
> 上错号了。。

噗😂 坐等大佬修复

**Comment by sirius-fan** [comment]
明确问题，现在刚改完两个意思能出一个，明天晚上我再改，需求就是把两个含义叠一起呗

**Comment by SOREMUZ** [comment]
> 明确问题，现在刚改完两个意思能出一个，明天晚上我再改，需求就是把两个含义叠一起呗

嗯嗯是的，叠一起就好了，麻烦大佬啦

**Comment by sirius-fan** [comment]
应该可以了，不过目前假设mdx不存在多次重定向，我不确定是否存在有极少数情况会多次重定向
![image](https://github.com/sirius-fan/FastWordQuery/assets/25720015/6bf1050d-39d6-4718-b5a6-a0eab8a40945)

**Comment by sirius-fan** [comment]
另外改了目录结构，复制src文件夹吧

**Comment by SOREMUZ** [comment]
> 另外改了目录结构，复制src文件夹吧

非常感谢，已经可以正常显示了

**Comment by SOREMUZ** [comment]
> 

发现了一个新问题，query“ ばつが悪い ”的时候，最后会变成这样


<img width="712" alt="image" src="https://github.com/sirius-fan/FastWordQuery/assets/64671591/3044c0c1-c944-4576-bbef-4a7c036596fd">

欧路词典里可以正常显示

**Comment by sirius-fan** [comment]
用欧陆是什么样子的，是没有下面的`@@@LINK=`，还是@@@后面的字都没有，就是这部分
![image](https://github.com/sirius-fan/FastWordQuery/assets/25720015/e71191a5-888f-4d0a-9de0-01b1aea652a9)

---
我用goldendict没查到这个词，是哪个词典，还有预期的正常情况是什么样子的
这个看起来应该就是多次重定向了。

**Comment by SOREMUZ** [comment]
> 用欧陆是什么样子的，是没有下面的`@@@LINK=`，还是@@@后面的字都没有，就是这部分 ![image](https://user-images.githubusercontent.com/25720015/258123611-e71191a5-888f-4d0a-9de0-01b1aea652a9.png)
> 
> 我用goldendict没查到这个词，是哪个词典，还有预期的正常情况是什么样子的 这个看起来应该就是多次重定向了。



不好意思没注意到是另一个词典 https://forum.freemdict.com/t/topic/11703
下载链接https://pan.baidu.com/s/1VlxfxCwB9VTC3eomEYki3g?pwd=2d2d

mdd有点大，下mdx应该也可以

预期的正常情况是这样的：
<img width="965" alt="image" src="https://github.com/sirius-fan/FastWordQuery/assets/64671591/ddeb633e-e0bc-4a5a-a405-e66dfa890f77">
<img width="795" alt="image" src="https://github.com/sirius-fan/FastWordQuery/assets/64671591/3fe92d13-a597-4001-844b-efdaefba283c">

还有就是搜　ばつ　的时候，不管是大辞泉还是我第一次发的那个新世纪日汉，anki里都无法query出内容，但欧路都可以正常显示的

<img width="637" alt="image" src="https://github.com/sirius-fan/FastWordQuery/assets/64671591/f6128bd0-cb48-4124-83a0-38dee994e231">

**Comment by sirius-fan** [comment]
ばつ查不到的问题我也发现了，昨天晚上的pr修复了，大辞泉这个问题需要递归查找的，我周末再改

**Comment by sirius-fan** [comment]
已修复

**Comment by SOREMUZ** [comment]
又发现了一个问题（不知道是大佬故意为之还是是bug），就是我已经设置好了一个字典并成功query后，换成另一个字典，如果这个字典里查不到同一个目标单词的话，之前query的内容就直接被删除了，之前的fwq是不会删除的

**Comment by sirius-fan** [comment]
是不是取消勾选了“跳过有值项”，如果勾选，我刚试了下应该不会删除

**Comment by SOREMUZ** [comment]
> 是不是取消勾选了“跳过有值项”，如果勾选，我刚试了下应该不会删除

就是感觉之前的内容留下来更方便，之前都是新词典覆盖旧词典的时候有新内容就更新，没有就留下之前的内容，不知道能不能改成之前的那种逻辑……

还有刚试了下如果勾选了跳过有值项，明明空白的区域也不会被query了，仍然是空白，好奇怪

**Comment by xavier-007** [comment]
这部分逻辑没有改过有可能是新api的问题，可能记忆错乱我记得之前就是这样的。

---

> 还有刚试了下如果勾选了跳过有值项，明明空白的区域也不会被query了，仍然是空白，好奇怪
![image](https://github.com/sirius-fan/FastWordQuery/assets/139991557/4c85cadb-740e-4a93-8805-542e09a98ad2)

![image](https://github.com/sirius-fan/FastWordQuery/assets/139991557/494e4c14-6a23-4831-84ab-a3d09ab749ef)
这个是anki新版本自身的问题，Ctrl+A 只能“显式”的删除内容，部分“隐式”的内容并不能删除，也就是实际上并不为空。
打开html编辑器能看到剩下的东西

---
> 就是感觉之前的内容留下来更方便，之前都是新词典覆盖旧词典的时候有新内容就更新，没有就留下之前的内容，不知道能不能改成之前的那种逻辑……

这个顶多做成新内容是空白时不覆盖，其他的不太可能，

**Comment by SOREMUZ** [comment]
完蛋了，我的牌组现在完全混乱了，我英日语混在一起的，现在势必有个语言query后会是空白，明天起床再研究下怎么弄吧，感谢大佬这么晚还回复我😂

**Comment by xavier-007** [comment]
问题不大，我做了个查找是否为空的判定，更新下试试吧，实在不行还可以回滚 : )

**Comment by SOREMUZ** [comment]
> 

感谢！又可以正常使用了


然后发现了一个新问题，类似于 ギロチン、アクロバット、ミイラ 这种后面跟着个括号带英文的词query不出来，之前是可以正常query的

欧路的新世纪日汉和大辞泉显示效果：


**ギロチン**


<img width="651" alt="image" src="https://github.com/sirius-fan/FastWordQuery/assets/64671591/00723bf3-8045-43c7-9025-d4333d5b245c">



**アクロバット**


<img width="647" alt="image" src="https://github.com/sirius-fan/FastWordQuery/assets/64671591/56f9082c-f9bd-41a2-97b7-950eb354441c">



**ミイラ**

<img width="650" alt="image" src="https://github.com/sirius-fan/FastWordQuery/assets/64671591/ffddcea6-db06-4fef-bb0d-fe5ce94824c3">



anki显示效果：空白

<img width="728" alt="image" src="https://github.com/sirius-fan/FastWordQuery/assets/64671591/66437af2-0aaa-4b6b-8be0-baaade1cb29a">

**Comment by sirius-fan** [comment]
小问题，用了个转大写去重，已修复

**Comment by SOREMUZ** [comment]
> 小问题，用了个转大写去重，已修复

大佬我又来了，不知道为什么我用[这个](https://forum.freemdict.com/t/topic/22477)或[这个](https://forum.freemdict.com/t/topic/22480)词典的时候，anki里query出来是空白，而且有时候空白的区域还是看上去有内容的空白

比如欧路测试词汇 翡翠
<img width="654" alt="image" src="https://github.com/sirius-fan/FastWordQuery/assets/64671591/c6a83593-47c6-41a1-97af-6810da8b5cf8">


anki 显示query成功了，但是是空白的
<img width="744" alt="image" src="https://github.com/sirius-fan/FastWordQuery/assets/64671591/363af5d2-77bc-48b9-905c-fdba29456ad4">

**Comment by sirius-fan** [comment]
词典也挺抽象 `@smk8-010943-0000` 能搜出翡翠的解释，已修复
https://github.com/sirius-fan/FastWordQuery/commit/333d007ac5933ce1588720bae5c464773ca88815

我在commit里带了issue连接，pull上来后github自动把issue关了，再有问题的话可以新开也可以重开。

**Comment by SOREMUZ** [comment]
> 词典也挺抽象 `@smk8-010943-0000` 能搜出翡翠的解释，已修复 [333d007](https://github.com/sirius-fan/FastWordQuery/commit/333d007ac5933ce1588720bae5c464773ca88815)
> 
> 我在commit里带了issue连接，pull上来后github自动把issue关了，再有问题的话可以新开也可以重开。

大佬你那边用smk8生成的单词有css吗，我这边单词没带上css，看了下没生成wrap.css这个文件，直接把原css文件拖进去也没生成
<img width="709" alt="image" src="https://github.com/sirius-fan/FastWordQuery/assets/64671591/9d4d3db6-7e9d-439d-9212-5b51c91a79c7">

**Comment by sirius-fan** [comment]
没注意，下午看看

**Comment by sirius-fan** [comment]
还是感觉词典不太规范，至少从前端上来讲（虽然我不太懂前端），一般约定俗成HTML 用双引号，JS 用单引号，这里搞个`<link rel='stylesheet' href='smk8.css' type='text/css'>` 单引号，后面又都是双引号就很怪，单双引号混用也不算语法错误就是不太规范，看起来就像制表符和空格混用一样难受😂。
已修复，但还没传，
我试试能不能把顺手把音频导入的问题解决下

**Comment by sirius-fan** [comment]
语音有点复杂，再说吧，css导入问题修复并上传了

**Comment by SOREMUZ** [comment]
> 语音有点复杂，再说吧，css导入问题修复并上传了

谢谢大佬！之前fwq是有一个导入本地词典语音的功能的，不过只能选择朗文6词典😂

**Comment by SOREMUZ** [comment]
大佬我在原作者那边开了个issue安利了一下你的fork，因为还有不知道已经有修复版的友友在那边回复我很久之前提的issue，希望不要介意😂
